// Company domain per xStock/Backpack symbol, for the nest-splash design's favicon-based ticker
// labels (`google.com/s2/favicons?domain=...`, see NestHero.tsx / README.md in nest-splash/).
// Covers the backend's curated universe (xstocks.service.ts NEST_UNIVERSE_ALLOWLIST +
// BACKPACK_UNIVERSE) — keep in sync with both.
export const TICKER_DOMAIN: Record<string, string> = {
  AAPLx: "apple.com",
  MSFTx: "microsoft.com",
  GOOGLx: "abc.xyz",
  AMZNx: "amazon.com",
  METAx: "meta.com",
  NVDAx: "nvidia.com",
  AVGOx: "broadcom.com",
  ORCLx: "oracle.com",
  NFLXx: "netflix.com",
  AMDx: "amd.com",
  PLTRx: "palantir.com",
  CRMx: "salesforce.com",
  ADBEx: "adobe.com",
  CSCOx: "cisco.com",
  INTCx: "intel.com",
  IBMx: "ibm.com",
  HPEx: "hpe.com",
  UNHx: "unitedhealthgroup.com",
  MRNAx: "modernatx.com",
  UBERx: "uber.com",
  ABNBx: "airbnb.com",
  SNAPx: "snap.com",
  SPOTx: "spotify.com",
  SHOPx: "shopify.com",
  RBLXx: "roblox.com",
  COINx: "coinbase.com",
  HOODx: "robinhood.com",
  MSTRx: "strategy.com",
  CRCLx: "circle.com",
  SPYx: "ssga.com",
  QQQx: "invesco.com",
  JPMx: "jpmorganchase.com",
  Vx: "visa.com",
  MAx: "mastercard.com",
  WMTx: "walmart.com",
  KOx: "coca-cola.com",
  PEPx: "pepsico.com",
  DISx: "disney.com",
  BAx: "boeing.com",
  XOMx: "exxonmobil.com",
  JNJx: "jnj.com",
  ABBVx: "abbvie.com",
  TSLAx: "tesla.com",
  HDx: "homedepot.com",
  LOWx: "lowes.com",
  MCDx: "mcdonalds.com",
  SBUXx: "starbucks.com",
  VZx: "verizon.com",
  TMUSx: "t-mobile.com",
  PFEx: "pfizer.com",
  MRKx: "merck.com",
  LLYx: "lilly.com",
  GILDx: "gilead.com",
  REGNx: "regeneron.com",
  BMYx: "bms.com",
  Fx: "ford.com",
  GMx: "gm.com",
  RIVNx: "rivian.com",
  DALx: "delta.com",
  UALx: "united.com",
  LUVx: "southwest.com",
  UPSx: "ups.com",
  FDXx: "fedex.com",
  CATx: "caterpillar.com",
  DEx: "deere.com",
  GEx: "geaerospace.com",
  HONx: "honeywell.com",
  LMTx: "lockheedmartin.com",
  RTXx: "rtx.com",
  GSx: "goldmansachs.com",
  MSx: "morganstanley.com",
  WFCx: "wellsfargo.com",
  Cx: "citigroup.com",
  NEEx: "nexteraenergy.com",
  DUKx: "duke-energy.com",
  CMCSAx: "comcast.com",
  WBDx: "wbd.com",
  TXNx: "ti.com",
  QCOMx: "qualcomm.com",
  LRCXx: "lamresearch.com",
  KLACx: "kla.com",
  Ox: "realtyincome.com",
  PLDx: "prologis.com",
  AMTx: "americantower.com",
  MARx: "marriott.com",
  // Backpack Securities/Sunrise — no "x" suffix, matches their real on-chain symbol
  SPCX: "spacex.com",
  MU: "micron.com",
  SNDK: "sandisk.com",
  NKE: "nike.com",
  SKHY: "skhynix.com",
  DRAM: "roundhillinvestments.com",
};

export function tickerDomain(symbol: string): string {
  return TICKER_DOMAIN[symbol] ?? "google.com";
}
